# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "Setting up build environment"
      - bash bin/setup.sh
      - echo "Building the Kolla image(s)"
      - bash bin/kolla-build.sh $IMAGE_REPO_NAME
      - bash bin/ecr-push.sh
