# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ca-central-1)
      - IMAGE_TAG="$RELEASE-$(date +%Y.%m.%d.%I.%M)"
  build:
    commands:
      - echo Build started on `date`
      - echo "Setting up build environment"
      - bash bin/setup.sh
      - echo "Building the Kolla image(s)"
      - bash bin/kolla-build.sh --registry $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com --push $IMAGE_REPO_NAME
